### ISSUE TITLE
Porting to Atmega16(L).

### ISSUE THREAD

**Issue by cbalint13** [ElTangas/jtag2updi#5]
Hi @ElTangas !

 Would like to ask a little bit of help related to the subject, will detail below.

1. There are some very cute USB sticks which could run jtag2updi like these [AVR-ICE Clones](https://www.aliexpress.com/item/AVR-JTAG-ICE-USB-Download-Programmer-Emulator-Aluminum-Shell-Over-Current-Protection-Wide-Voltage-Buffer-Chip/32656234883.html), comming with a little atmega16L chip, CH340 usb-serial and have some HC245 buffers (not all useful for UPDI, but can be avoided).

2. The device come with a burnt in bootloader that is actice for a few seconds at boot time, so i managed to write a simple python script that is able to flash/read (.hex) anything in these little USB sticks without touching the electronics/pcb at all.

**The problem**

  a. In order to port on atmega16l timer1 or timer2 should be used and timer0 should to be avoided.

  b. Unfortunate is that even on original atmega328p (on a plain arduino uno) timer1 and timer2 variants gets me to "Illegal MCU State" but timer0 always works !

  c. Obviously, since i am unable to make it work with timer1 or timer2 on original 328p cant make it on atmel16.

**The request**

 If have some little time can look into why timer1 and timer2 variants of original code leads to wrong "Illegal MCU state" ? 

I prepared here all the code for all three variants of timer usage [HERE](http://openrisc.rdsor.ro/jtag2updi/). Obviously I spent lot of time figuring out why 1:1 same code works well with timer0 and why fails e.g. on timer2 (perfectly similar) on the very same 328p board.

**ToDo**

 - Would it be possible to use TimerX with ISR() ? That would allow to control any pin not only dedicated OCRX pins. I wasnt able to make such setup and lack of a good digital analyser hardened the task a lot.

**Comment by ElTangas** [comment]
I will look into the timer2 problem, you are right, it's very similar to timer0 so it should work.

Regarding using an ISR, this might mess up the timings, yes, I have the equipment to do it (logic analyser) but a bit short on time at the moment. I'll try to implement an ISR version when I have more time.

edit:
I just remembered I disabled a bunch of unused peripherals on the sys_init() function located in the jtag2updi.cpp file. This includes timers 1 and 2, so maybe that's why you can't get them to work here.

I always do this out of habit to save power, even if it's not needed in this case.

**Comment by cbalint13** [comment]
* I got it in PR #6 . Very strange issue. Will be back with Atmega16 port and it's complete easy solution for those cool AVR-JTAG-ICE USB sticks.


Thank You !

**Comment by ElTangas** [comment]
I believe this issue is fixed now.
